### ISSUE TITLE
Using same setup gives duplication error in generated graphql.ts file

### ISSUE THREAD

**Issue by wetendorff** [datocms/next-minimalistic-photography#1]
Using the same setup as this demo project gives "Duplicate identifier"-errors in the generated graphql.ts when used with my datocms project.

From by graphql.ts with duplicated CreatedAtAsc, CreatedAtDesc, UpdatedAtAsc, UpdatedAtDesc):

```javascript
export enum TopNavModelOrderBy {
  CreatedAtAsc = '_createdAt_ASC',
  CreatedAtDesc = '_createdAt_DESC',
  FirstPublishedAtAsc = '_firstPublishedAt_ASC',
  FirstPublishedAtDesc = '_firstPublishedAt_DESC',
  IsValidAsc = '_isValid_ASC',
  IsValidDesc = '_isValid_DESC',
  PublicationScheduledAtAsc = '_publicationScheduledAt_ASC',
  PublicationScheduledAtDesc = '_publicationScheduledAt_DESC',
  PublishedAtAsc = '_publishedAt_ASC',
  PublishedAtDesc = '_publishedAt_DESC',
  StatusAsc = '_status_ASC',
  StatusDesc = '_status_DESC',
  UnpublishingScheduledAtAsc = '_unpublishingScheduledAt_ASC',
  UnpublishingScheduledAtDesc = '_unpublishingScheduledAt_DESC',
  UpdatedAtAsc = '_updatedAt_ASC',
  UpdatedAtDesc = '_updatedAt_DESC',
  CreatedAtAsc = 'createdAt_ASC',
  CreatedAtDesc = 'createdAt_DESC',
  HrefAsc = 'href_ASC',
  HrefDesc = 'href_DESC',
  IdAsc = 'id_ASC',
  IdDesc = 'id_DESC',
  PositionAsc = 'position_ASC',
  PositionDesc = 'position_DESC',
  TitleAsc = 'title_ASC',
  TitleDesc = 'title_DESC',
  UpdatedAtAsc = 'updatedAt_ASC',
  UpdatedAtDesc = 'updatedAt_DESC'
}
```

I fixed it by adding nameConvention to the graphql.config.js file:

```javascript
config: {
  namingConvention: {
    enumValues: 'keep',
  },
},
```

I think it would be great if you could add this to the demo project. It would probably save people a lot of time.

 I don't know if you consider "keep" as the best practice regarding naming conventions.

**Comment by stefanoverna** [comment]
You probably have a DatoCMS project created before January 1st, 2023. On new projects, the error is not present as we got rid of the duplicates: https://www.datocms.com/product-updates/api-cleanup-for-freshly-created-projects

But we'll add a note on the README, thanks!
